---
title: Exercises and Resources
number_sections: TRUE
date: "`r format(Sys.time(), '%d %B, %Y')`"
author: "Eawag Summer School in Environmental Systems Analysis"
output:
  html_document:
    number_sections: FALSE
    toc: TRUE
    toc_depth: 2
---

# General information

- How to approach the exercises?
- Should I use R or Julia (or Python)?

## R resources

- how to install the packages

## Julia resources

- how to install the packages

# Example models and data

...


# Exercises

- [Exercises 0](exercise_0.html): review of probability
  calculus, basics of R and Julia

- [Exercises 1](exercise_1.html): deriving and implementing likelihood
  functions, sensitivity analysis

- [Exercises 2](exercise_2.html): Bayesian computations, MCMC

- [Exercises 3](exercise_3.html): Adaptive Bayesian computations, MCMC

#### Advances Topics

- [Exercises 4](exercise_4.html): Inference for Hierarchical models
  with STAN and JAGS

- [Exercises 5](exercise_5.html): Approximative Bayesian Computation
  (ABC)


# Solutions

- [Solutions 0](exercise_0_solution.html)

- [Solutions 1](exercise_1_solution.html)

- [Solutions 2](exercise_2_solution.html)

- [Solutions 3](exercise_3_solution.html)


# I've found a bug or typo!

If you find any typos, errors, confusing instructions, bad solutions,
or you have general suggestions how to
improve the exercises, please open an
[issue here](https://github.com/scheidan/SiamSummerSchoolExercises/issues)
(PRs are welcome too). Thanks a lot!

# Version info {.tabset}

The solutions have been compiled with the follow versions:

## R
```{r, echo=FALSE}
sI <- sessionInfo()
print(sI, RNG = FALSE, locale = FALSE)
```

## Julia
```{julia, echo=FALSE}
using InteractiveUtils: versioninfo
versioninfo()
```

```{julia , echo=FALSE}
import Pkg
Pkg.activate("../.")
Pkg.status()
```
