### Solution {.tabset}

#### R

a.
```{r}

## Loading data
## ----------------------------------------------
growth.dat <- read.table("../../data/model_growth.csv", header=TRUE)
C_M <- growth.dat$C_M
C_S <- growth.dat$C_S
```

```{r}
## Plotting data
## ----------------------------------------------
plot(growth.dat$t, growth.dat$C_S, type="b", xlab="Time", ylab="Concentration")
lines(growth.dat$t, growth.dat$C_M, type="b", pch=17, col=2)
legend("topright", legend=c("Substrate", "Microorganisms"), col=c(1,2), pch=c(1,17), lty=1)

```

b.
```{r}

## Combining Data
## ----------------------------------------------
## Data for new row
y <- rnorm(nrow(growth.dat))

## Add the row to the dataframe
growth.dat.2 <- cbind(growth.dat, C_new = y)
head(growth.dat.2)

```
#### Julia
a.
```{julia, results ='hide'}
using CSV
using DataFrames
pwd()
```
Given your working directory, go to the desired file with a relative path. Remember that `..` allows to come one step back.
```{julia, results ='hide'}
growth_dat = CSV.read(joinpath("..", "..", "data", "model_growth.csv"),
                      DataFrame)
# show(growth_dat, allrows=true) if you want to see all you data
```
Extraction of a column can be done with the following syntax.
```{julia, results = 'hide'}
C_M = growth_dat[:, "C_M"]
C_S = growth_dat[:, "C_S"]
time = growth_dat[:, "t"]
## or alternatively
time = growth_dat.t
```
Plotting
```{julia, out.width = '80%'}
plot(time, C_M,
    labels="Microorganisms",
    xlabel="Time",
    ylabel="Concentration");
plot!(time, C_S,
    labels="Substrat")
```
b.
```{julia, results = 'hide'}
# generate some data
C_new = rand(nrow(growth_dat))

# add new column
growth_dat.Cnew = C_new
```

#### Python

a.
```{python}
import pandas as pd

## Loading data
# Specify the path to the CSV file
file_path = r"../../data/model_growth.csv"

# Load the CSV file into a pandas DataFrame
growth_dat = pd.read_csv(file_path, sep=" ")

# Access the 'C_M' and 'C_S' columns from the DataFrame
t = growth_dat['t']
C_M = growth_dat['C_M']
C_S = growth_dat['C_S']
```

```{python}
## Plotting data
# Set the figure size (width, height) in inches
plt.figure(figsize=(14, 6))

# Create a line plot for 'C_S' against 't'
sns.lineplot(x=t, y=C_S, marker='o', label='Substrate')

# Create a line plot for 'C_M' against 't'
sns.lineplot(x=t, y=C_M, marker='^', color='red', label='Microorganisms')

# Add x-axis and y-axis labels
plt.xlabel('Time')
plt.ylabel('Concentration')

# Add a legend to the plot
plt.legend(loc='upper right')

# Display the plot
plt.show()
```

b.
```{python}
# Number of rows in the growth_dat dataframe
n = len(growth_dat)

# Generate an array of normally distributed random numbers with the same number of rows as growth_dat
y = np.random.normal(size=n)

# Add the new row to the dataframe as a new column named 'C_new'
growth_dat['C_new'] = y

# Display the first few rows of the updated dataframe
print(growth_dat.head())
```
