## Solution {.tabset}

### R

```{r, results="hide"}
library(FME)
library(IDPmisc)
neg.log.post <- function(par) -logposterior.monod(par)
```

The mean of the prior seems to be a reasonable point to start the
sampler. Alternatively, we could try to find point of the maximum
posterior density with an optimizer. For the covariance matrix of
the jump distribution we use the standard deviation of the prior and assume independence.

```{r}
par.init <- prior.monod.mean
jump.cov <- diag(prior.monod.sd/2)

par.init <- prior.monod.mean
jump.cov <- diag(prior.monod.sd/2)

AMDR <- FME::modMCMC(f         = neg.log.post,
                     p         = par.init,
                     jump      = jump.cov,
                     niter     = 10000,
                     updatecov = 10,
                     ntrydr    = 3
                     )

## plot chains
plot(AMDR)

## 2d marginals
pairs(AMDR$pars)
IDPmisc::ipairs(AMDR$pars)
```

### Julia

```{julia}
using ComponentArrays
using AdaptiveMCMC
using MCMCChains
using Plots
using StatsPlots

θinit = ComponentVector(r_max = 2.5, K=1.4, sigma=0.25) # use prior mean
res = adaptive_rwm(θinit, logposterior_monod,
                   10_000;
                   algorithm = :am,
                   b=1,   # length of burn-in. Set to 1 for no burn-in.
                   );
# convert to MCMCChains for summary and plotting
chn = Chains(res.X', labels(θinit))
plot(chn)
corner(chn)
```
